In [1]:
import numpy as np

In [5]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
z = np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
z=np.random.random((3,3,3))
print(z)

[[[0.20528977 0.34395341 0.60858849]
  [0.26468183 0.98700344 0.75264521]
  [0.88399707 0.08536681 0.04954885]]

 [[0.48606807 0.5144685  0.76167356]
  [0.84302896 0.60408625 0.4345911 ]
  [0.00248637 0.37148898 0.51048262]]

 [[0.03494309 0.9358496  0.02205581]
  [0.52134612 0.09220268 0.7815146 ]
  [0.61617158 0.62827534 0.97028236]]]


- 전체 요소가 30인 numpy 3차원 배열 만들기
- 그 배열의 평균값 구하기

In [15]:
z= np.random.random(30)
print(z)

[0.59711008 0.78629353 0.60368829 0.84231307 0.69988816 0.26820014
 0.12515013 0.14252681 0.25310995 0.73534404 0.73667759 0.94537222
 0.34161137 0.99732476 0.80880885 0.49592462 0.88890516 0.37587497
 0.68718099 0.09240702 0.5577288  0.65260648 0.36753837 0.11578764
 0.75693505 0.57425646 0.57134645 0.94289675 0.65805872 0.49182321]


In [16]:
m=z.mean()
print(m)

0.570422988676642


In [17]:
mid_score = [10,20,30]
final_score=[70,80,90]

In [18]:
total=mid_score + final_score
print(total)

[10, 20, 30, 70, 80, 90]


In [19]:
mid_score = np.array([10,20,30])
final_socre = np.array([70,80,90])

In [20]:
total = mid_score + final_score
print(total)

[ 80 100 120]


In [21]:
print("시험 성적의 합계 : ",total)

시험 성적의 합계 :  [ 80 100 120]


In [22]:
print("시험 성적의 평균 : ",total/2)

시험 성적의 평균 :  [40. 50. 60.]


In [23]:
array_a=[0,1,2,3,4,5,6,7,8,9]
array_b=[0,1,2,3,4,5,6,7,8,9]
array_c=[1,2,4,6,8]

In [25]:
array_a = np.array([0,1,2,3,4,5,6,7,8,9])
array_b = np.array([0,1,2,3,4,5,6,7,8,9])   #array_b=np.array(range(10))
array_c = np.array([1,2,4,6,8])             #array_c=np.array(range(0,10,2))

In [26]:
array_c.shape

(5,)

In [27]:
array_c.ndim

1

In [28]:
array_c.dtype

dtype('int32')

In [29]:
array_c.size

5

In [30]:
array_c.itemsize #배열내의 원소크기가 4byte야

4

In [31]:
salary = np.array([220,250,230])

In [32]:
salary=salary+100

In [33]:
salary

array([320, 350, 330])

In [34]:
salary=salary*2
print(salary)

[640 700 660]


In [35]:
palyers=[[170,76.4],[183,86.2],[171,73.5],[176,80.1]]

In [41]:
np_players=np.array(palyers)

In [37]:
np_players

array([[170. ,  76.4],
       [183. ,  86.2],
       [171. ,  73.5],
       [176. ,  80.1]])

In [45]:
print("몸무게가 80이상인 선수의 정보",np_players[np_players[:,1]>=80])

몸무게가 80이상인 선수의 정보 [[183.   86.2]
 [176.   80.1]]


In [60]:
print("키가 180이상인 선수의 정보",np_players[np_players[:,0]>=180.0]) #다 가져오고, 첫번째 열 값이랑 비교할게

키가 180이상인 선수의 정보 [[183.   86.2]]


In [61]:
revenue_in_yen = [320,250,500,180,300,200,370,110,400,600,350,150,450,220,310,420,160,270,440,550,
                 170,330,280,330,580,100,355,420,570,220]

In [62]:
yen_array = np.array(revenue_in_yen)

In [63]:
yen_array.size

30

In [65]:
won_array = yen_array*9.7

In [66]:
won_array

array([3104. , 2425. , 4850. , 1746. , 2910. , 1940. , 3589. , 1067. ,
       3880. , 5820. , 3395. , 1455. , 4365. , 2134. , 3007. , 4074. ,
       1552. , 2619. , 4268. , 5335. , 1649. , 3201. , 2716. , 3201. ,
       5626. ,  970. , 3443.5, 4074. , 5529. , 2134. ])

In [67]:
dollar = [32,25,50,68,30,20,37,88,40,60,35,15,45,22,31,42,85,27,44,55,
                 65,75,95,70,80,90,85,42,57,22]

In [68]:
dollar_array = np.array(dollar)

In [71]:
won_array2 = dollar_array*1391

In [72]:
won_array2

array([ 44512,  34775,  69550,  94588,  41730,  27820,  51467, 122408,
        55640,  83460,  48685,  20865,  62595,  30602,  43121,  58422,
       118235,  37557,  61204,  76505,  90415, 104325, 132145,  97370,
       111280, 125190, 118235,  58422,  79287,  30602])

In [73]:
total = won_array*9.7+won_array*1391

In [74]:
total

array([4347772.8 , 3396697.5 , 6793395.  , 2445622.2 , 4076037.  ,
       2717358.  , 5027112.3 , 1494546.9 , 5434716.  , 8152074.  ,
       4755376.5 , 2038018.5 , 6114055.5 , 2989093.8 , 4211904.9 ,
       5706451.8 , 2173886.4 , 3668433.3 , 5978187.6 , 7472734.5 ,
       2309754.3 , 4483640.7 , 3804301.2 , 4483640.7 , 7880338.2 ,
       1358679.  , 4823310.45, 5706451.8 , 7744470.3 , 2989093.8 ])

In [75]:
new_total=total*10
new_total

array([43477728.        , 33966975.        , 67933950.        ,
       24456222.        , 40760370.        , 27173580.        ,
       50271122.99999999, 14945469.        , 54347159.99999999,
       81520740.        , 47553764.99999999, 20380185.        ,
       61140555.        , 29890938.        , 42119049.        ,
       57064517.99999999, 21738864.        , 36684333.        ,
       59781876.        , 74727345.        , 23097542.99999999,
       44836406.99999999, 38043012.        , 44836406.99999999,
       78803382.        , 13586790.        , 48233104.49999999,
       57064517.99999999, 77444703.        , 29890938.        ])

In [78]:
new_total=new_total.astype("int64")
new_total

array([43477728, 33966975, 67933950, 24456221, 40760370, 27173579,
       50271122, 14945469, 54347159, 81520740, 47553764, 20380185,
       61140555, 29890938, 42119049, 57064517, 21738864, 36684333,
       59781876, 74727345, 23097542, 44836406, 38043012, 44836406,
       78803382, 13586789, 48233104, 57064517, 77444703, 29890938],
      dtype=int64)

In [80]:
new_array= new_total*10
new_array

array([434777280, 339669750, 679339500, 244562210, 407603700, 271735790,
       502711220, 149454690, 543471590, 815207400, 475537640, 203801850,
       611405550, 298909380, 421190490, 570645170, 217388640, 366843330,
       597818760, 747273450, 230975420, 448364060, 380430120, 448364060,
       788033820, 135867890, 482331040, 570645170, 774447030, 298909380],
      dtype=int64)

In [82]:
sad_days_revenue=new_array[new_array<=500000000]

In [83]:
sad_days_revenue

array([434777280, 339669750, 244562210, 407603700, 271735790, 149454690,
       475537640, 203801850, 298909380, 421190490, 217388640, 366843330,
       230975420, 448364060, 380430120, 448364060, 135867890, 482331040,
       298909380], dtype=int64)