In [1]:
import numpy as np

### BMI 구하기
- delimiter : 구분기호

In [3]:
data = np.loadtxt('height_weight.txt',delimiter=',')    #txt파일 불러오는법, 주소까지 적고 구분자 표시해주기
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [5]:
data.shape

(2, 10)

In [6]:
#데이터를 키와 몸무게로 나누기
height_cm=data[0]
print(height_cm)

[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]


In [7]:
weight_kg=data[1]
print(weight_kg)

[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]


In [8]:
#키를 cm가 아니라 m로 표현해보기
height_m = height_cm/100
print(height_m)

[1.752 1.803 1.75  1.692 1.852 1.88  1.776 1.782 1.77  1.79 ]


In [9]:
BMI = weight_kg/(height_m*height_m)
BMI

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [13]:
data= np.loadtxt('ratings.txt',delimiter='::',dtype='int')
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [14]:
#data의 크기(모양새),차원, 원소 개수를 확인해봅시다.
data.shape  #데이터크기(모양새)

(1000209, 4)

In [15]:
data.size #데이터 원소개수

4000836

In [16]:
data.ndim  #데이터 차원

2

In [18]:
### 1번 유저의 전체 정보 출력
data[data[:,0]==1]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [20]:
# id 정보만 가져오기
# 결과 : [1 1 1 .... 6040 6040 ..]
user_id = data[:,0]
print(user_id)

[   1    1    1 ... 6040 6040 6040]


#### 전체 사용자들의 평점 평균 구하기

In [21]:
#전체 자료에서 평점 가져오기
ratings = data[:,2]
print(ratings)

[5 3 3 ... 5 4 4]


In [22]:
np.mean(ratings)

3.581564453029317

- 1번 사용자의 평점 평균 구하기
- 인덱싱한 자료에서 평점만 가져오기
- 가져온 평점 평균 구하기

In [27]:
user_1= data[data[:,0]==1]

In [28]:
user_1=id_1[:,2]
print(np.mean(user_1))

4.188679245283019
