In [2]:
import pandas as pd
import numpy as np

In [4]:
arr1 = np.arange(2,51,2)
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [5]:
arr_ex01 = np.zeros((4,4))
arr_ex01                           #기본형이 실수로 출력

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
arr_ex02 = np.ones((10,10))
arr_ex02

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
arr_ex03 = np.full((7,4),3)
arr_ex03                   #입력을 정수값으로 했기 때문에 정수로 출력

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [11]:
arr_ex04 = np.arange(3,101,3)
arr_ex04

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
print(arr_ex04.size)   #원소갯수구하기

33


In [12]:
arr_ex05 = arr_ex04.reshape(3,11)
print(arr_ex05)

[[ 3  6  9 12 15 18 21 24 27 30 33]
 [36 39 42 45 48 51 54 57 60 63 66]
 [69 72 75 78 81 84 87 90 93 96 99]]


In [13]:
print(arr_ex05.shape)

(3, 11)


In [14]:
import random

- 0~1 사이의 값을 랜덤하게 가지는 6*4배열 생성
- 1~100사이의 값을 랜덤하게 가지는 5*5배열 생성
- astype을 사용하여 2번의 배열을 실수형태의 원소를 가지는 배열로 바꾸시오

In [22]:
rand_arr = np.random.rand(6,4)
rand_arr

array([[0.97278244, 0.37310503, 0.66992319, 0.78632652],
       [0.59109765, 0.58328392, 0.35596246, 0.82221279],
       [0.31009553, 0.61370819, 0.56696964, 0.00433905],
       [0.62987679, 0.25939238, 0.56870872, 0.47568431],
       [0.64034579, 0.96367364, 0.80914036, 0.56685798],
       [0.81948739, 0.55667811, 0.09235189, 0.76956241]])

In [21]:
randint_arr = np.random.randint(1,101,(5,5))
randint_arr

array([[53, 10, 74, 64, 46],
       [22,  8, 50, 71, 77],
       [57, 53, 21, 70, 69],
       [65, 20, 84, 26, 39],
       [89, 89, 99, 32, 83]])

In [23]:
arr_float = randint_arr.astype('float64')
arr_float

array([[53., 10., 74., 64., 46.],
       [22.,  8., 50., 71., 77.],
       [57., 53., 21., 70., 69.],
       [65., 20., 84., 26., 39.],
       [89., 89., 99., 32., 83.]])

- 주어진 배열에서 3,4,8,9 원소만 가져오기

In [25]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [27]:
x[:,3:]   #n차원의 배열에서 인덱싱하려면 [ 행구간(:)  , 열구간(:) ] 지정

array([[3, 4],
       [8, 9]])

In [28]:
x[1,1:4]

array([6, 7, 8])

In [29]:
y = np.arange(15).reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [34]:
y[:,3]

array([ 3,  8, 13])

In [35]:
y[1,:]

array([5, 6, 7, 8, 9])

In [37]:
y[:2,1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [38]:
arr2d = np.arange(1,13).reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
arr2d[arr2d<=5]

array([1, 2, 3, 4, 5])

In [41]:
# 3의 배수 추출하기
arr2d[arr2d %3 == 0]  # & : And , | : OR

array([ 3,  6,  9, 12])

In [42]:
x = np.random.randint(1,100,size=10)
x

array([13, 58, 89, 18, 32, 73, 96,  7, 27, 47])

In [43]:
#2의 배수만 추출하기 
x[x%2 ==0]

array([58, 18, 32, 96])

In [45]:
#60보다 큰 수 추출하기
x[x>60]

array([89, 73, 96])

In [46]:
# 30보다 크고 70보다 작은수 추출하기
x[(x>30) &(x<70)]

array([58, 32, 47])

In [50]:
# 60보다 크거나 홀수인 수 추출하기
x[(x>60) | (x%2 !=0)]

array([13, 89, 73, 96,  7, 27, 47])

In [51]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [52]:
len(temp)

31

In [54]:
#기온이 25도를 넘는 날은 몇 일인가?
a=temp[(temp>25.0)]
print(a)

[25.4 27.6 29.7 26.7 25.1 25.9 25.6 26.9 28.6 28.  25.1 26.7 28.1 26.5
 26.3 25.9 28.4 26.1 27.5 28.1 25.8]


In [55]:
len(a)

21

In [62]:
len(temp[temp>25.0])

21

In [63]:
np.sum(temp>25.0)    #boolean으로 보는법

21

In [ ]:
#기온이 25도를 넘는 날의 평균 기온은?

In [58]:
average=sum(a)/len(a)
average

26.857142857142858

In [64]:
np.mean(temp[temp>25.0])

26.857142857142858

### 정렬 : sort

#### 1차원 정렬

In [65]:
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [66]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [68]:
np.sort([1,10,5,8,2,4,3,6,8,7,9])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [69]:
np.sort(arr)[::-1]   # 내림차순정렬 [::-1] 외우자아~!

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [70]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [72]:
arr2=np.sort(arr) #정렬된 변수는 일회성이기 때문에 새로운 변수에 저장해야 정렬된 순서로 사용 가능하다
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

#### 2. N차원정렬

In [73]:
arr2d=np.array([[5,6,7,8],
              [4,3,2,1],
              [10,9,12,11]])

In [74]:
arr2d.shape

(3, 4)

#### 2-1. 열정렬(왼쪽에서 오른쪽으로) - axis(축)


In [75]:
np.sort(arr2d,axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

#### 2-1. 행정렬(위에서 아래로)

In [77]:
np.sort(arr2d,axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [78]:
y=np.random.randint(100,size=(3,5))
print(y)

[[ 2 72 90  3  9]
 [45  1 58 41 97]
 [10 56  8 68 89]]


- y원소들의 평균, 합, 최대값, 최소값, 분산, 중앙값, 표준편차를 구해봅시다

In [79]:
np.mean(y)  # y.mean()이랑 같은값

43.266666666666666

In [80]:
np.sum(y)

649

In [81]:
np.max(y)

97

In [82]:
np.min(y)

1

In [83]:
np.var(y)

1174.8622222222223

In [87]:
np.median(y) #중앙값은 y.median()계산 불가

45.0

In [86]:
np.std(y)

34.27626324765029